device:
  name: "EX-G Pro TrackBall"

remaps:
  meta:
    description: back button -> left meta
    input:
      type: key
      code: BTN_BACK
    output:
      - key: KEY_LEFTMETA

  enter:
    description: forward button -> enter
    input:
      type: key
      code: BTN_FORWARD
    output:
      - key: KEY_ENTER
        hold: null

  ctrl-tab:
    description: back button -> ctrl-tab in sub mode
    input:
      type: key
      code: BTN_BACK
    output:
      - key: KEY_LEFTCTRL
        hold: 200
      - key: KEY_TAB
        hold: null

mode_switches:
  modes:
    - name: default
      remaps:
        - meta
        - enter
    - name: sub
      remaps:
        - ctrl-tab
        - enter
  input:
    type: key
    code: BTN_TASK
